### ISSUE TITLE
Please, describe the project status

### ISSUE THREAD

**Issue by paluh** [robertdp/purescript-wire-react-router#1]
Hi @robertdp!

I've just found this repo and it seems very interesting (as usual :-)). Would you be so kind and write a few words about the library status? Is it WIP? Is it usable?

Thanks in advance!

**Comment by robertdp** [comment]
It's missing docs, and I have made a few improvements that are as-yet untested, but it should be usable now.

Almost everything you need to know to use it is in this type signature: https://github.com/robertdp/purescript-wire-react-router/blob/master/generated-docs/md/Wire.React.Router.md#makerouter

**Comment by paluh** [comment]
> It's missing docs, and I have made a few improvements that are as-yet untested, but it should be usable now.
> Almost everything you need to know to use it is in this type signature (...)

Thanks a lot! I think that README with this signature alone and a sentence like "async router for _react-basic_" could be quite informative.

I think that I've a requirement in my new application which can be implemented using this routing model. Do you think that I'm going to be able to handle "save on exit" modal using this router (in other words I want to ask user if he wants to save latest version of his work before leaving)?

**Comment by robertdp** [comment]
> I think that README with this signature ...

That's good, I'll add that when I have a moment next.

> Do you think that I'm going to be able to handle "save on exit" modal using this router?

This isn't a use case that even crossed my mind, but actually yes I think it's possible. It should be pretty straightforward to add a "routing blocker" that can be controlled from deeper in the application. Then the `onRouteChange` logic can interact with this blocker and decide what to do next.

**Comment by robertdp** [comment]
I did a little cleaning and polishing, and added a README and a very basic example. Please have a look: https://github.com/robertdp/purescript-wire-react-router/blob/master/README.md

**Comment by paluh** [comment]
Looks really good! Thanks a lot!

Your simple starting example is really valuable from my perspective. I wonder if it could be somehow shared / included in the _purescript-cookbook_ to increase discoverability...

P.S.
I really want to replace my messy routing logic with your clean router API now :-)

**Comment by paluh** [comment]
I'm closing this for now as the project status seems to be clear - it is "production ready!" :-)
