### ISSUE TITLE
You also support hash-based routing

### ISSUE THREAD

**Issue by i-am-the-slime** [robertdp/purescript-wire-react-router#11]
Yet the README specifically mentions push-state. I barely passed on this library but now I'm intrigued.

Am I looking at this wrong (maybe I need to read the README until the end?)

**Comment by robertdp** [comment]
Yes, it supports both push-state- and hash-based routing. Originally it was push-state only, but the concept of "drivers" was added a couple of months ago specifically to enable the use of hashes. It could potentially even support more exotic methods, like remote handling of routing over a socket.

In the example repo you would only need to change the following line to use `Hash.makeDriver`:
https://github.com/robertdp/purescript-web-router-example/blob/master/src/App/Router.purs#L36

**Comment by i-am-the-slime** [comment]
Thanks, that's what I tried, but it looks like makeDriver for hash is not effectful so it turns into a let 👍🏻
