### ISSUE TITLE
Drop `react-basic` dependency

### ISSUE THREAD

**Issue by paluh** [robertdp/purescript-wire-react-router#8]
It seems that the only part which ties this lib to _react-basic_ is a small piece of the router constructor. I think that we can abstract this away and instead of providing `component :: JSX` (which internally handles subscribing / unsubscribing of the router) return `subscribe :: Effect (Effect Unit)` (or only `unsubscribe :: Effect Unit` - I'm not sure) as a part of the `makeRouter` result.

Then we are going to have _wire-react-router_ without _wire_ and without _react_ which sounds more like a _web-router_ or something :-P

**Comment by robertdp** [comment]
Yeah, then it would just be a pushstate router with support for async transitions. No UI library-specific dependencies. But is there anybody who wants this?
